apiVersion: v1
kind: Service
metadata:
  name: microservice-utilisateur-service
spec:
  selector:
    app: microservice-utilisateur
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
